### ISSUE TITLE
Get the screen capture to work

### ISSUE THREAD

**Issue by cdneeee** [cdneeee/mibot#1]

**Comment by BigSkyCoder2003** [comment]
Hello. I tried to reproduce this issue, but the program appeared to work correctly according to your documentation. Could I have a more specific description of the issue you are having?

**Comment by cdneeee** [comment]
> Hello. I tried to reproduce this issue, but the program appeared to work correctly according to your documentation. Could I have a more specific description of the issue you are having?


Sorry, created this accidentally, just getting to know project section on GitHub, thanks
